package net.chickensell;

import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import java.util.*;

final class TurkishNames {
    private static final Map<String,String> WORDS = new HashMap<>();
    private static final Map<String,String> ENCHANTS = new HashMap<>();
    static {
        put("ACACIA","Akasya","AMETHYST","Ametist","ANCIENT","Kadim","ANDESITE","Andezit","APPLE","Elma","AZALEA","Açelya","BAMBOO","Bambu","BASALT","Bazalt","BED","Yatak","BEEF","Dana Eti","BEETROOT","Pancar","BIRCH","Huş","BLACK","Siyah","BLUE","Mavi","BONE","Kemik","BOOKSHELF","Kitaplık","BRICK","Tuğla","BROWN","Kahverengi","BUDDING","Tomurcuklanan","CACTUS","Kaktüs","CAKE","Kek","CARROT","Havuç","CHARCOAL","Odun Kömürü","CHERRY","Kiraz","CHICKEN","Tavuk","CHISELED","Kesilmiş","CHORUS","Koro","CLAY","Kil","COAL","Kömür","COBBLESTONE","Kırıktaş","COCOA","Kakao","COD","Morina","CONCRETE","Beton","COOKED","Pişmiş","COPPER","Bakır","CRIMSON","Kızıl","CUT","Kesilmiş","CYAN","Camgöbeği","DARK","Koyu","DEEPSLATE","Derin Kayrak","DIAMOND","Elmas","DIORITE","Diyorit","DIRT","Toprak","DRIED","Kurutulmuş","DRIPSTONE","Damlataş","ECHO","Yankı","EMERALD","Zümrüt","ENCHANTED","Büyülü","END","End","ENDSTONE","End Taşı","FISH","Balık","FLOWERING","Çiçekli","GILDED","Yaldızlı","GLASS","Cam","GLOW","Parlayan","GOLD","Altın","GOLDEN","Altın","GRANITE","Granit","GRASS","Çim","GRAVEL","Çakıl","GRAY","Gri","GREEN","Yeşil","HONEY","Bal","HONEYCOMB","Bal Peteği","ICE","Buz","INGOT","Külçe","IRON","Demir","JUNGLE","Orman","KELP","Su Yosunu","LAPIS","Lapis","LAZULI","Lazuli","LIGHT","Açık","LOG","Kütüğü","MAGENTA","Eflatun","MANGROVE","Mangrov","MELON","Karpuz","MOSS","Yosun","MOSSY","Yosunlu","MUD","Çamur","MUSHROOM","Mantar","MUTTON","Koyun Eti","NETHER","Nether","NETHERITE","Netherit","NUGGET","Parçası","OAK","Meşe","OBSIDIAN","Obsidyen","ORANGE","Turuncu","ORE","Cevheri","PACKED","Sıkıştırılmış","PINK","Pembe","PLANKS","Tahtaları","PODZOL","Podzol","POLISHED","Cilalı","PORKCHOP","Domuz Pirzolası","POTATO","Patates","POWDER","Tozu","PRISMARINE","Prizmarin","PUFFERFISH","Balon Balığı","PUMPKIN","Balkabağı","PURPLE","Mor","QUARTZ","Kuvars","RABBIT","Tavşan","RAW","Ham","RED","Kırmızı","REDSTONE","Kızıltaş","SAND","Kum","SANDSTONE","Kumtaşı","SALMON","Somon","SCRAP","Hurdası","SEA","Deniz","SEEDS","Tohumları","SHARD","Parçası","SLAB","Basamak","SMOOTH","Düzgün","SOUL","Ruh","SPONGE","Sünger","SPRUCE","Ladin","STAIRS","Merdiven","STONE","Taş","STRIPPED","Soyulmuş","SUGAR","Şeker","SUSPICIOUS","Şüpheli","SWEET","Tatlı","TERRACOTTA","Terrakota","TROPICAL","Tropikal","TUFF","Tüf","WARPED","Çarpık","WART","Siğili","WHEAT","Buğday","WHITE","Beyaz","WOOD","Odunu","WOOL","Yün","YELLOW","Sarı","BLOCK","Bloğu","BRICKS","Tuğlaları","BOTTLE","Şişesi","BUCKET","Kovası","CLUSTER","Kümesi","FRUIT","Meyvesi","PIE","Turtası","SOUP","Çorbası","STEW","Yahnisi","SLICE","Dilimi","EGG","Yumurta","BERRIES","Meyveleri","SUGAR_CANE","Şeker Kamışı");
        ench("protection","Koruma","fire_protection","Ateş Koruması","feather_falling","Tüy Düşüşü","blast_protection","Patlama Koruması","projectile_protection","Mermi Koruması","respiration","Solungaç","aqua_affinity","Su Adaptasyonu","thorns","Dikenler","depth_strider","Derin Koşucu","frost_walker","Kırağı Yürüyüşü","binding_curse","Bağlanma Laneti","sharpness","Keskinlik","smite","Darbe","bane_of_arthropods","Eklembacaklıların Kıyameti","knockback","Savurma","fire_aspect","Alevden Çehre","looting","Ganimet","sweeping_edge","Süpürücü Kenar","efficiency","Verimlilik","silk_touch","İpeksi Dokunuş","unbreaking","Kırılmazlık","fortune","Servet","power","Güç","punch","Yumruk","flame","Alev","infinity","Sonsuzluk","luck_of_the_sea","Deniz Şansı","lure","Ayartma","loyalty","Sadakat","impaling","Şişleme","riptide","Girdap","channeling","Yıldırım Yönlendirmesi","multishot","Çoklu Atış","quick_charge","Hızlı Dolum","piercing","Delme","mending","Tamir","vanishing_curse","Kaybolma Laneti","soul_speed","Ruh Hızı","swift_sneak","Hızlı Süzülme","density","Yoğunluk","breach","İhlal","wind_burst","Rüzgar Patlaması");
    }
    private static void put(String... a){for(int i=0;i+1<a.length;i+=2)WORDS.put(a[i],a[i+1]);}
    private static void ench(String... a){for(int i=0;i+1<a.length;i+=2)ENCHANTS.put(a[i],a[i+1]);}
    static String material(Material m){
        String exact=exact(m.name()); if(exact!=null)return exact;
        StringBuilder out=new StringBuilder();
        for(String w:m.name().split("_")){if(!out.isEmpty())out.append(' ');out.append(WORDS.getOrDefault(w,title(w)));}
        return out.toString();
    }
    static String enchant(Enchantment e){String k=e.getKey().getKey();return ENCHANTS.getOrDefault(k,titleWords(k));}
    private static String exact(String n){return switch(n){case "GRASS_BLOCK"->"Çim Bloğu";case "OAK_LOG"->"Meşe Kütüğü";case "SPRUCE_LOG"->"Ladin Kütüğü";case "BIRCH_LOG"->"Huş Kütüğü";case "JUNGLE_LOG"->"Orman Ağacı Kütüğü";case "ACACIA_LOG"->"Akasya Kütüğü";case "DARK_OAK_LOG"->"Koyu Meşe Kütüğü";case "CHERRY_LOG"->"Kiraz Kütüğü";case "DIAMOND"->"Elmas";case "EMERALD"->"Zümrüt";case "IRON_INGOT"->"Demir Külçesi";case "GOLD_INGOT"->"Altın Külçesi";case "NETHERITE_INGOT"->"Netherit Külçesi";case "COAL"->"Kömür";case "WHEAT"->"Buğday";case "SUGAR_CANE"->"Şeker Kamışı";case "COOKED_BEEF"->"Pişmiş Dana Eti";case "BEEF"->"Çiğ Dana Eti";case "COOKED_CHICKEN"->"Pişmiş Tavuk";case "CHICKEN"->"Çiğ Tavuk";case "COOKED_MUTTON"->"Pişmiş Koyun Eti";case "MUTTON"->"Çiğ Koyun Eti";case "COOKED_PORKCHOP"->"Pişmiş Domuz Pirzolası";case "PORKCHOP"->"Çiğ Domuz Pirzolası";case "GOLDEN_APPLE"->"Altın Elma";case "ENCHANTED_GOLDEN_APPLE"->"Büyülü Altın Elma";case "GOLDEN_CARROT"->"Altın Havuç";case "BREAD"->"Ekmek";case "COOKIE"->"Kurabiye";case "BAKED_POTATO"->"Fırında Patates";case "PUMPKIN_PIE"->"Balkabağı Turtası";default->null;};}
    private static String title(String s){s=s.toLowerCase(Locale.ROOT);return Character.toUpperCase(s.charAt(0))+s.substring(1);}
    private static String titleWords(String s){StringBuilder r=new StringBuilder();for(String w:s.split("_")){if(!r.isEmpty())r.append(' ');r.append(title(w));}return r.toString();}
    private TurkishNames(){}
}
